mask_method:  'sam_with_gt' #'sam'
track_method: 'superglue' #'pips'
gt_prompt: True

track_frame_thr: 5
object_min_points: 5
num_ref: 1
prompt_points_num: 8
neg_points_num: 100
iters: 8
resample: True

data:
    nclass: 81
    normal_size: [480, 640] # min_size, max_size
    box_padding: [100, 100]
    
sam_model_path: 'sam_model_path/mobile_sam.pt'
pips_model_path: 'pips_model_path/model-000200000.pth'

model:
  superpoint:
    descriptor_dim: 256
    nms_radius: 4
    keypoint_threshold: 0.005
    max_keypoints: -1
    remove_borders: 4
    path: 'model/weights/superpoint_v1.pth'

  superglue:
    descriptor_dim: 256
    weights: 'indoor'
    sinkhorn_iterations: 100
    match_threshold: 0.2
    path: 'model/weights/superglue_outdoor.pth'
